---
repos:
  - repo: https://github.com/Bahjat/pre-commit-golang
    rev: c3086eea8af86847dbdff2e46b85a5fe3c9d9656
    hooks:
      - id: go-fmt-import
        args: ['-local', 'github.com/cmsgov/easi-shared']

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.46.2
    hooks:
      - id: golangci-lint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
