name: Run pre-commit hooks

on:
  workflow_call:

env:
  GO_VERSION: "1.16.6"

jobs:
   lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Pre-commit checks
        uses: pre-commit/action@9b88afc9cd57fd75b655d5c71bd38146d07135fe
        with:
          extra_args: --all-files
