name: Run Tests

on:
  workflow_call:

jobs:
  server_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Set up go
        uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a
        with:
          go-version-file: './go.mod'
          cache: true
      - name: Run go tests
        run: scripts/test-go.sh
