name: Run Tests

on:
  workflow_call:

jobs:
  server_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Set up go
        uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f
        with:
          go-version-file: './go.mod'
          cache: true
      - name: Run go tests
        run: scripts/test-go.sh
